# æ•´ä¸ªæµç¨‹çš„åå­—
name: Package CI

# è§¦å‘æ—¶æœºï¼Œåœ¨ main åˆ†æ”¯ push æ“ä½œè§¦å‘
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
      - .npmignore
      
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
      - .npmignore

permissions:
  contents: write
  pull-requests: write

# ä»»åŠ¡
jobs:
  CIBUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # install
      - name: Install dependencies
        run: |
           pnpm install
                 
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type": "chore", "section":"ğŸ« Chores | å…¶ä»–æ›´æ–°", "hidden": false},{"type": "revert", "section":"âª Reverts | å›é€€", "hidden": false},{"type": "feat", "section": "âœ¨ Features | æ–°åŠŸèƒ½", "hidden": false},{"type": "fix", "section": "ğŸ› Bug Fixes | Bug ä¿®å¤", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"ğŸ“ Documentation | æ–‡æ¡£", "hidden": false},{"type": "style", "section":"ğŸ’„ Styles | é£æ ¼", "hidden": false},{"type": "refactor", "section":"ğŸ’„ Styles | é£æ ¼", "hidden": false},{"type": "perf", "section":"âš¡ Performance Improvements | æ€§èƒ½ä¼˜åŒ–", "hidden": false},{"type": "test", "section":"âœ… Tests | æµ‹è¯•", "hidden": false},{"type": "build", "section":"ğŸ‘·â€ Build System | æ„å»º", "hidden": false},{"type": "ci", "section":"ğŸ”§ Continuous Integration | CI é…ç½®", "hidden":false}]' 
        
      - name: Build
        run: npm run buildAll
      - name: Upload build dist
        uses: actions/upload-artifact@v3
        with:
          name: my-dist # è‡ªå®šä¹‰åç§°
          # path: my-dist.tgz # æ„å»ºäº§å‡ºç‰©çš„è·¯å¾„

      - name: Download build dist
        uses: actions/download-artifact@v3
        with:
          name: my-dist # è‡ªå®šä¹‰åç§°
          # path:  # æ„å»ºäº§å‡ºç‰©çš„è·¯å¾„
      
      - name: Extract Artifact
        run: tar xvf my-dist.tgz --strip-components=1

      - name: Commit Changes
        run: |
          git config --local user.email 1750263786@qq.com"
          git config --local user.name "UzumakiHan"
          git commit -m "build: Update build dist" -a || true
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}
     
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
        
